import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./context/AuthContext";
import { Navbar } from "@/components/nav/Navbar";
import Footer from "@/components/footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Travel Buddy",
  description: "Generated by create next app",
};

const navProps = {
  webName : "TravelBuddy",
  subtitle : "alo",
  itemOnNav : [
    {
      itemName: "Post",
      linkTo : "/post"
    },
    {
      itemName: "Place",
      linkTo : "/place/da-nang"
    },
    {
      itemName: "Chat",
      linkTo : "/chat"
    },
  ]
}

const dataFooter = [
  {
    "footerTitle": "Support",
    "footerItems": [
      { "itemName": "Manage your trips", "linkTo": "#" },
      { "itemName": "Contact Customer Service", "linkTo": "#" },
      { "itemName": "Safety Resource Center", "linkTo": "#" }
    ]
  },
  {
    "footerTitle": "Discover",
    "footerItems": [
      { "itemName": "Genius loyalty program", "linkTo": "#" },
      { "itemName": "Seasonal and holiday deals", "linkTo": "#" },
      { "itemName": "Travel articles", "linkTo": "#" },
      { "itemName": "Booking.com for Business", "linkTo": "#" },
      { "itemName": "Traveller Review Awards", "linkTo": "#" },
      { "itemName": "Car rental", "linkTo": "#" },
      { "itemName": "Flight finder", "linkTo": "#" },
      { "itemName": "Restaurant reservations", "linkTo": "#" },
      { "itemName": "Booking.com for Travel Agents", "linkTo": "#" }
    ]
  },
  {
    "footerTitle": "Terms and settings",
    "footerItems": [
      { "itemName": "Privacy Notice", "linkTo": "#" },
      { "itemName": "Terms of Service", "linkTo": "#" },
      { "itemName": "Accessibility Statement", "linkTo": "#" },
      { "itemName": "Partner dispute", "linkTo": "#" },
      { "itemName": "Modern Slavery Statement", "linkTo": "#" },
      { "itemName": "Human Rights Statement", "linkTo": "#" }
    ]
  },
  {
    "footerTitle": "Partners",
    "footerItems": [
      { "itemName": "Extranet login", "linkTo": "#" },
      { "itemName": "Partner help", "linkTo": "#" },
      { "itemName": "List your property", "linkTo": "#" },
      { "itemName": "Become an affiliate", "linkTo": "#" }
    ]
  },
  {
    "footerTitle": "About",
    "footerItems": [
      { "itemName": "About Booking.com", "linkTo": "#" },
      { "itemName": "How We Work", "linkTo": "#" },
      { "itemName": "Sustainability", "linkTo": "#" },
      { "itemName": "Press center", "linkTo": "#" },
      { "itemName": "Careers", "linkTo": "#" },
      { "itemName": "Investor relations", "linkTo": "#" },
      { "itemName": "Corporate contact", "linkTo": "#" },
      { "itemName": "Content guidelines and reporting", "linkTo": "#" }
    ]
  }
]
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Navbar webName={navProps.webName} subtitle={navProps.subtitle} itemOnNav={navProps.itemOnNav} />
          {children}
          <Footer props={dataFooter}/>
        </AuthProvider>
      </body>

    </html>
  );
}
